# Generated by Django 5.2 on 2025-04-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_task_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day_of_week',
        ),
    ]
